### ISSUE TITLE
Implement Authentication

### ISSUE THREAD

**Issue by RaymondDashWu** [Insight-Generator/DS-ML-DL#6]
- [ ] Create frontend page that will interact with external user management system
- [ ] Research external user management systems (Auth0, Oauth, etc.)

**Comment by mattluu** [comment]
To clarify this a bit, we don't need to build a separate page when using these services as often times, they require to have the page themselves. For example, Auth0 login will either include the page or include a component we use to add the login. So this means it's really just taking advantage of that page and making sure that we have a way to tie our models to those users.

As for external user management systems, I also want to clarify that `OAuth` is a standard, not a specific external user management solution. Alternatives to `Auth0` are things like `Amazon Cognito`, `Okta`, `Keycloak`, `OneLogin`, and probably more. There is an `OAuth.io` however.

**Comment by mattluu** [comment]
I have moved this to our `bilight` repo as issue 2 (not sure how to link it). I will close this issue and continue there
